# generated by datamodel-codegen:
#   filename:  user_role_changed_event.json
#   timestamp: 2024-03-10T09:02:53+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class EventTitleUserRoleChanged(Enum):
    USER_ROLE_CHANGED = 'USER.ROLE_CHANGED'


class UserRoles(Enum):
    EMPLOYEE = 'EMPLOYEE'
    ADMIN = 'ADMIN'
    MANAGER = 'MANAGER'


class UserRoleChangedDataSchema(BaseModel):
    public_id: str = Field(..., title='Public Id')
    old_role: Optional[UserRoles] = None
    new_role: UserRoles


class UserProducer(Enum):
    AUTH_SERVICE = 'AUTH_SERVICE'


class UserRoleChangedEventSchema(BaseModel):
    version: Optional[int] = Field(1, title='Version')
    produced_at: Optional[datetime] = Field(None, title='Produced At')
    title: Optional[EventTitleUserRoleChanged] = 'USER.ROLE_CHANGED'
    data: UserRoleChangedDataSchema
    producer: Optional[UserProducer] = 'AUTH_SERVICE'
