import enum


@enum.unique
class Permissions(str, enum.Enum):
    CAN_READ_USERS = "CAN_READ_USERS"
    CAN_UPDATE_USER = "CAN_UPDATE_USER"
    CAN_READ_SELF_TASKS = "CAN_READ_SELF_TASKS"
    CAN_READ_ALL_TASKS = "CAN_READ_ALL_TASKS"
    CAN_ASSIGN_NEW_TASKS = "CAN_ASSIGN_NEW_TASKS"
    CAN_UPDATE_SELF_TASKS = "CAN_UPDATE_SELF_TASK"
