"""initial

Revision ID: 206dc6e41665
Revises: 
Create Date: 2024-02-25 14:15:36.349709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206dc6e41665'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('beak_shape', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'ADMIN', 'MANAGER', name='userroles'), server_default=sa.text("'EMPLOYEE'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beak_shape'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_refresh_token')
    op.drop_table('user')
    # ### end Alembic commands ###
